### PR TITLE
active projects added

### LINKED ISSUE #6: add active projects column.
Add active project column and have buttons on the both side.

### PR DESCRIPTION
**Pull request by codetheorem**
Fixes #6 .
image

### CODE REVIEW

**Comment by Amankumar29** [comment]
great job @codetheorem :)

**Comment by Amankumar29** [comment]
can you please add the details for frontend and ios project.

**Comment by codetheorem** [comment]
Ok sure

**Comment by codetheorem** [comment]
@Amankumar29 I have added ios and frontend projects with their link.

**Comment by anubhavsingh16** [comment]
@Amankumar29 please have a look.

**Pull request merged**
