### PR TITLE
Aim para

### LINKED ISSUE #10: adding image and aim of the catalyst.

### PR DESCRIPTION
**Pull request by vinayaksh42**
fixes #10 
Screenshot
chrome_gjovgJpt8Y

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@vinayaksh42 bro this is Aim of `Open Source Events- frontend` repo.  For now, just make a heading `Aim of our organization`.

**Comment by vinayaksh42** [comment]
Okay

**Comment by vinayaksh42** [comment]
@anubhavsingh16 i have left blank space at the position of aim paragraph.

**Comment by anubhavsingh16** [comment]
Okk great

**Pull request merged**
