### PR TITLE
Events added

### PR DESCRIPTION
**Pull request by codetheorem**
# Proposed changes

I have added events section.

# Types of changes

**Delete irrelevant options.**

- [x] New feature (non-breaking change which adds functionality) 

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# Screenshots

image

### CODE REVIEW

**Comment by codetheorem** [comment]
image

**Comment by Amankumar29** [comment]
@anubhavsingh16 views?
i think that "i want to announce" should be changed to "Team catalyst announces an offer..."

**Comment by codetheorem** [comment]
@Amankumar29 we can change that afterwards only image has to be changed.

**Comment by anubhavsingh16** [comment]
> @anubhavsingh16 views?
> i think that "i want to announce" should be changed to "Team catalyst announces an offer..."

Yes, @codetheorem please change to we announce.

**Pull request merged**
